apiVersion: v1
kind: Service
metadata:
  name: go-app-external
spec:
  selector:
    app: go-app
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 30002
  type: NodePort 
