apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-db
  template:
    metadata:
      labels:
        app: go-db
    spec:
      containers:
      - name: go-db
        image: postgres:16.0
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: clinicreservationsystem
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
