apiVersion: v1
kind: Service
metadata:
  name: go-db-service
  labels:
    app: go-db
spec:
  selector:
    app: go-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30003
  type: NodePort
